[build]
  # 1. Tells Netlify to go into this folder first
  base = "Frontend"
  
  # 2. Tells Netlify to output the built site from this folder
  # (This path is relative to 'base', so it means Frontend/dist)
  publish = "dist"
  
  # 3. The command to build your React app
  command = "npm run build"

# 4. Fixes the "Page Not Found" refresh bug for React apps
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200